version: "3.9"
services:
  database:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=keyoarbcat
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  nodejs-express:
    profiles:
      - nodejs-express
      - compare-frontend
      - js-vue
      - rust-yew
      - rust-yew-solution
    build: ./backend/nodejs/express
    volumes:
      - ./backend/nodejs/express:/code/
    depends_on:
      - database
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=keyboardcat
      - SALT_ROUNDS=10
      - DB_CONNECTION=postgresql://postgres:keyoarbcat@database
  api-test:
    profiles:
      - nodejs-express
      - rust-axum
    build: ./integration-tests/backend-tests
    volumes:
      - ./integration-tests/backend-tests:/code/
    depends_on:
      - rust-axum
    environment:
      - API_PORT=3000
      - API_URI=http://rust-axum
      - JWT_SECRET=keyboardcat
      - DB_CONNECTION=postres://postgres:keyoarbcat@database/postgres
  js-vue:
    profiles:
      - js-vue
      - compare-frontend
    build: ./frontend/js/vue
    volumes:
      - ./frontend/js/vue:/code/
    depends_on:
      - nodejs-express
    expose:
      - "8080"
    ports:
      - "8080"
    environment:
      - VUE_APP_API_URI=http://localhost:3000
  rust-axum:
    profiles:
      - rust-axum
    build: ./backend/rust/learning_axum
    volumes:
      - ./backend/rust/learning_axum:/code
    depends_on:
      database:
        condition: service_healthy
    expose:
      - 3000
    ports:
      - 3001:3000
volumes:
  db-data:
