[package]
name = "todo_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
stylist = {version = "0.10.1", features = ["yew", "macros"]}
yew-router = "0.16.0"