[package]
name = "a_better_hello_world_architecture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
gloo = "0.6.1"
serde = "1.0.136"
serde_json = "1.0.79"